### ISSUE TITLE
Issues with Shadow DOM?

### ISSUE THREAD

**Issue by IORoot** [straker/livingcss#19]
Hi there,
So, I've been using your livingcss (which is awesome BTW) and it's been working locally without a hitch, but I've started trying to run it on my server and the livingcss gulp process doesn't seem to be working quite right...
I've stripped everything down to a single livingcss comment block and the gulp process only has a src > livingcss > destination, but still things are not as they should be.

The first issue is that when I look at the Devtools on server, it doesn't seem to be loading the shadow DOM and any Shady DOM Styles:
![screen shot 2016-08-12 at 15 01 40](https://cloud.githubusercontent.com/assets/8770616/17624724/c65af620-609d-11e6-8877-619383d24edf.png)
(The local file doesn't have this).

My gulpfile looks like this:

```javascript
// Tell node.js about these modules.
var gulp         = require('gulp');
var include      = require("gulp-include");
var concat       = require("gulp-concat");
var sass         = require('gulp-sass');
var livingcss    = require('gulp-livingcss');
var autoprefixer = require('gulp-autoprefixer');

// CONCAT / SASS Compile into CSS file.
gulp.task('livingcss-sass', function(){
    return gulp.src([
            './resources/assets/sass/molecules/swatch.scss',
    ])
        .pipe(concat('styles.scss'))
        .pipe(sass())
        .pipe(gulp.dest('./public/livingcss/src/'))
});

//Run the Living Stylesheet creator.
gulp.task('livingcss',['livingcss-sass'], function () {
    gulp.src('./public/livingcss/src/styles.css')
        .pipe(livingcss())
        .pipe(gulp.dest('./public/livingcss/dist/'))
});
```

The swatch.scss file has the following:

```css
/**
 * Swatch
 *
 * Everything to do with the combinations of Atom components into Molecules.
 *
 * @section Swatch
 * @page Molecules
 *
 * @example
 * <div class="rk-swatch">
 *  <div class="rk-swatch-col"></div>
 * </div>
 */

$rk-white :                    #f7f7f7;

.rk-swatch {

  // Display & Positioning

  // Box Model
  width : 150px;
  margin: 10px;
  padding-bottom: 5px;

  // Colour
  background: $rk-white;

}

.rk-swatch-col {
  display: block;
  // Box Model
  width: 100px;
  height: 150px;

  background: #990000;
}
```

This creates the result:

![screen shot 2016-08-12 at 15 10 47](https://cloud.githubusercontent.com/assets/8770616/17625049/091b37ee-609f-11e6-8ace-17e5c886eabf.png)

Which is not the result that should be displayed. The styling for the `rk-swatch-col` DIV is not applied and the shadow DOM is not present.

Not sure what's happening at all. I've got it all successfully running locally and the results are fine. 

Is this an issue here?
