### ISSUE TITLE
Generated <h1> font-family differs from rendered on a page

### ISSUE THREAD

**Issue by Kamilius** [straker/livingcss#28]
The generated from SASS to CSS styles for `h1` are as follows:
```css
h1 {
  font-family: "Helvetica Neue Light", "Helvetica Neue Regular", "Helvetica Neue", "Helvetica", "Arial", sans-serif;
  font-size: 2.25rem;
  line-height: 1.375em; }
```
But on a page, in styles section of devtools, font-family looks like this:
```css
h1.livingcss-example {
    font-family: &quot;
    font-size: 2.25rem;
    line-height: 1.375em;
}
```

Is there any legit way to include custom font files into styleguide? (Your default template is taken as base).
